name: validate

on:
  pull_request:
    paths:
      - .github/workflows/validate.yaml
      - .github/renovate.json
      - default.json
  push:
    branches:
      - main

jobs:
  validate:
    uses: int128/renovate-config-validator-workflow/.github/workflows/validate.yaml@main
    with:
      config: .github/renovate.json default.json
